### ISSUE TITLE
No such file or directory: 'semgrep-core' when installing semgrep with pipx

### ISSUE THREAD

**Issue by underyx** [returntocorp/semgrep-vscode#35]
I use pipx so that global python tools each have their own virtualenv and don't conflict with each other. The binary ends up here, but semgrep-core is not exposed in the same way:

```terminal
$ which semgrep
/Users/underyx/.local/bin/semgrep
$ which semgrep-core
semgrep-core not found
```

The vscode extension gives me this error on load

```terminal
Traceback (most recent call last):
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/commands/lsp.py", line 53, in lsp
    run_server()
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/lsp/server.py", line 263, in run_server
    server.start()
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/lsp/server.py", line 246, in start
    self.std_reader.listen(self.on_std_message)
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/pylsp_jsonrpc/streams.py", line 40, in listen
    message_consumer(json.loads(request_str.decode('utf-8')))
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/lsp/server.py", line 200, in on_std_message
    self.start_ls()
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/lsp/server.py", line 86, in start_ls
    self.core_process = subprocess.Popen(
                        ^^^^^^^^^^^^^^^^^
  File "/Users/underyx/.asdf/installs/python/3.11.0/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/underyx/.asdf/installs/python/3.11.0/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'semgrep-core'
```

It seems like semgrep CLI works because it manages to find the core binary which is at `/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.11/site-packages/semgrep/bin/semgrep-core`.

**Comment by ajbt200128** [comment]
This is fixed in 1.21.0 of semgrep!
